Repository LocalOrbit/localorbit, pull requests merged in 2018-08, with the labels that each got.

#3360 updates rubocop config
  .rubocop.yml
  config/rubocop.disabled.yml
  config/rubocop.enabled.yml
Labels: +1 weston

#3359 3338 newsletter target fix
  Gemfile.lock
  app/controllers/admin/fees_controller.rb
  app/controllers/admin/market_qb_profile_controller.rb
  app/controllers/admin/order_items_controller.rb
  app/controllers/admin/organizations_controller.rb
  app/controllers/sessions/organizations_controller.rb
  app/interactors/create_supplier_org_for_producer.rb
  app/interactors/send_fresh_sheet.rb
  app/models/organization.rb
  app/models/registration.rb
  app/models/user.rb
  app/presenters/report_presenter.rb
  app/views/admin/organizations/_form.html.erb
  app/views/products/alternative_order_page.html.erb
  lib/imports/product_helpers.rb
  lib/tasks/production-copy.rake
  spec/factories.rb
  spec/interactors/send_fresh_sheet_spec.rb
  spec/models/registration_spec.rb
  spec/models/user_spec.rb
Labels: +1 rob, +1 weston, ready for review

#3362 Fixes/cleans prod db cleansing task
  lib/tasks/production-copy.rake
Labels: +1 weston, ready for review

#3452 heroku binstubs
  README.md
  bin/prod
  bin/production
  bin/staging
Labels: +1 rob, +1 weston

#3364 Reduce the noise in Rollbar
  config/initializers/rollbar.rb
Labels: +1 ivar, +1 rob
