Repository LocalOrbit/localorbit, pull requests merged in 2018-07, with the labels that each got.

#3279 [LO-1139] Mailer previews
  app/interactors/payment_made_email_confirmation.rb
  app/interactors/payment_received_email_confirmation.rb
  app/mailers/payment_mailer.rb
  config/application.rb
  config/environments/staging.rb
  config/locales/mailers/payment_mailer.yml
  lib/financials/payment_notifier.rb
  spec/lib/financials/payment_notifier_spec.rb
  spec/mailers/payment_mailer_spec.rb
  spec/mailers/previews/application_preview.rb
  spec/mailers/previews/payment_preview.rb
Labels: +1 ivar

#3285 Lo 1140 drop unnecessary pdfs from emails
  app/interactors/send_order_emails.rb
  app/interactors/send_update_emails.rb
  app/mailers/order_mailer.rb
  spec/mailers/order_mailer_spec.rb
Labels: +1 rob, +1 weston, ready for release

#3303 minor refactoring to order_mailer
  app/mailers/order_mailer.rb
Labels: +1 rob

#3307 Rob fixing some feature specs for #3300
  app/interactors/add_market_manager.rb
  app/views/admin/products/_filters.html.erb
  spec/features/admin/filter_products_spec.rb
  spec/features/admin/managing_market_managers_spec.rb
  spec/features/admin/managing_markets_spec.rb
  spec/spec_helper.rb
  spec/support/multiselect_helpers.rb
  spec/support/sorting_helpers.rb
Labels: +1 weston, ready for review

#3323 A dead_code! helper to find candidates for deletion
  app/controllers/admin/financials/market_payments_controller.rb
  app/controllers/application_controller.rb
  lib/dead_code.rb
Labels: +1 ivar, +1 rob

#3319 Some temporary basic webhook logging
  lib/payment_provider/handlers/async_handler.rb
Labels: +1 ivar

#3353 Search config to be for ag and rg instead of ack
  .ackrc
  .ignore
Labels: +1 ivar

#3322 Add more org info in 'New organization registration' email to fix #3299
  app/decorators/organization_decorator.rb
  app/mailers/market_mailer.rb
  app/models/organization.rb
  app/views/market_mailer/registration.html.erb
  config/locales/decorators/organization.yml
  spec/decorators/organization_decorator_spec.rb
  spec/factories.rb
  spec/mailers/market_mailer_spec.rb
Labels: +1 ivar, +1 weston

#3344 Show correct branding and confirm link when a user registers
  app/interactors/send_email_confirmation_request.rb
  app/models/registration.rb
  app/models/user.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  spec/features/registration_spec.rb
  spec/models/registration_spec.rb
  spec/models/user_spec.rb
Labels: +1 ivar, +1 weston
